### ISSUE TITLE
Request GitHub KYC-2271272653@qq.com

### ISSUE THREAD

**Issue by RayWangQvQ** [DigitalPlatDev/US.KG#102]
### KYC Using Your GitHub Account

Ensure your GitHub account meets the following requirements:

- [x] I have starred this repository (required).
- [x] Not a new GitHub account; it already has some repositories and stars.
- [x] This is my first US.KG NIC Panel account.
- [x] I promise not to use the domain name for criminal or abusive purposes.
- [x] I understand that GitHub KYC requires a waiting period for review.

**Your Account Details (US.KG NIC Panel):**
- Your full name: Peter Hessler
- Username: zai7lou
- Account Registration Email: 2271272653@qq.com
- Reason for Registering the .US.KG Domain Name: Using the domain to learn to build a website (personal blog) to meet my college major requirements

After submission, we will process your request ASAP.

**Comment by EdwardLab** [comment]
Approved, you may now login to US.KG Panel (We use scripts to automatically approve or deny. If you have any questions, please email contact@nic.us.kg)

**Comment by EdwardLab** [comment]
Approved, you may now login to US.KG Panel (We use scripts to automatically approve or deny. If you have any questions, please email contact@nic.us.kg)

**Comment by EdwardLab** [comment]
Approved, you may now login to US.KG Panel (We use scripts to automatically approve or deny. If you have any questions, please email contact@nic.us.kg)

**Comment by RayWangQvQ** [comment]
Okey, thanks.
