### ISSUE TITLE
Request GitHub KYC-13837629419@163.com

### ISSUE THREAD

**Issue by gwant333** [DigitalPlatDev/US.KG#10844]
![微信截图_20241010103811](https://github.com/user-attachments/assets/05da8e5f-aa1e-4be3-a6df-85d47e6ceb90)
### KYC Using Your GitHub Account

We use automated scripts to approve requests. Please make sure your GitHub account meets the following requirements (all are required):

- [ ] I have starred this repository.
- [ ] The issue title must be: Request GitHub KYC - Your US.KG Panel registered email. This ensures our automated script can detect your registered email.
- [ ] This is not a new GitHub account; it has existing repositories and stars.
- [x] This is my first US.KG NIC Panel account.
- [ ] I promise not to use the domain name for criminal or abusive purposes.

**Your Account Details (US.KG NIC Panel):**

Please fill out the following information; otherwise, your request will not be processed:

- Username: 
- Account Registration Email: 
- Reason for Registering the .US.KG Domain Name:

**Comment by gwant333** [comment]
[记事本.txt](https://github.com/user-attachments/files/17321083/default.txt)

**Comment by gwant333** [comment]
![微信截图_20241010103811](https://github.com/user-attachments/assets/dfa22f0b-daf5-4fdf-bab9-c8612effd341)

**Comment by EdwardLab** [comment]
Do not upload private information, I will delete it
