### ISSUE TITLE
Request GitHub KYC-906514912@qq.com

### ISSUE THREAD

**Issue by wfxzf** [DigitalPlatDev/US.KG#112]
### KYC Using Your GitHub Account

Ensure your GitHub account meets the following requirements:

- [ ] I have starred this repository (required).
- [x] Not a new GitHub account; it already has some repositories and stars.
- [ ] This is my first US.KG NIC Panel account.
- [ ] I promise not to use the domain name for criminal or abusive purposes.
- [ ] I understand that GitHub KYC requires a waiting period for review.

**Your Account Details (US.KG NIC Panel):**
- Your full name: du jingrong
- Username: wfxzf
- Account Registration Email: 906514912@qq.com
- Reason for Registering the .US.KG Domain Name:used for Nas ddns

After submission, we will process your request ASAP.

**Comment by EdwardLab** [comment]
Approved, you may now login to US.KG Panel (We use scripts to automatically approve or deny. If you have any questions, please email contact@nic.us.kg)

**Comment by EdwardLab** [comment]
Approved, you may now login to US.KG Panel (We use scripts to automatically approve or deny. If you have any questions, please email contact@nic.us.kg)

**Comment by EdwardLab** [comment]
Approved, you may now login to US.KG Panel (We use scripts to automatically approve or deny. If you have any questions, please email contact@nic.us.kg)
