### ISSUE TITLE
Request GitHub KYC-mimictearx@gmail.com

### ISSUE THREAD

**Issue by markintouch** [DigitalPlatDev/US.KG#114]
### KYC Using Your GitHub Account

Ensure your GitHub account meets the following requirements:

- [x] I have starred this repository (required).
- [x] Not a new GitHub account; it already has some repositories and stars.
- [x] This is my first US.KG NIC Panel account.
- [x] I promise not to use the domain name for criminal or abusive purposes.
- [x] I understand that GitHub KYC requires a waiting period for review.

**Your Account Details (US.KG NIC Panel):**
- Your full name: Mark Antony
- Username: mimictear
- Account Registration Email: mimictearx@gmail.com
- Reason for Registering the .US.KG Domain Name:Personal use. Build website.

After submission, we will process your request ASAP.

**Comment by EdwardLab** [comment]
Sorry, your GitHub account is too new. Please consider using other methods for KYC, Thanks :) (We use scripts to automatically approve or deny. If you have any questions, please email contact@nic.us.kg)

**Comment by markintouch** [comment]
Sorry to hear that an github account created in 2014 is too new.
 "created_at": "2014-05-18T14:51:16Z"

regards
Mark

________________________________
发件人: Edward Hsing ***@***.***>
发送时间: 星期一, 六月 3, 2024 01:21
收件人: DigitalPlatDev/US.KG ***@***.***>
抄送: markintouch ***@***.***>; Author ***@***.***>
主题: Re: [DigitalPlatDev/US.KG] Request GitHub ***@***.*** (Issue #114)


Sorry, your GitHub account is too new. Please consider using other methods for KYC, Thanks :) (We use scripts to automatically approve or deny. If you have any questions, please email ***@***.******@***.***>)

―

**Comment by EdwardLab** [comment]
Our auto script is based on the number of projects and stars
Which your account doesn't have much repos
