### ISSUE TITLE
Request GitHub KYC-maimang0536@gmail.com

### ISSUE THREAD

**Issue by maimang0536** [DigitalPlatDev/US.KG#117]
### KYC Using Your GitHub Account

Ensure your GitHub account meets the following requirements:

- [Y] I have starred this repository (required).
- [Y] Not a new GitHub account; it already has some repositories and stars.
- [Y] This is my first US.KG NIC Panel account.
- [Y] I promise not to use the domain name for criminal or abusive purposes.
- [Y] I understand that GitHub KYC requires a waiting period for review.

**Your Account Details (US.KG NIC Panel):**
- Your full name: jack wang
- Username: maimang0536
- Account Registration Email: maimang0536@gmail.com
- Reason for Registering the .US.KG Domain Name: study Exchange

After submission, we will process your request ASAP.

**Comment by EdwardLab** [comment]
Sorry, your GitHub account is too new. Please consider using other methods for KYC, Thanks :) (We use scripts to automatically approve or deny. If you have any questions, please email contact@nic.us.kg)
