### ISSUE TITLE
Request GitHub Donate KYC-ninethyearsold@gmail.com

### ISSUE THREAD

**Issue by NINETHOUSANDYEARSOLD** [DigitalPlatDev/US.KG#12488]
Donation amount:

Make sure the title format is "Request GitHub Donate KYC-YOUR_EMAIL@EXAMPLE.COM", After that, you can submit your request! You may also attach a screenshot of the donation receipt for faster processing.

**Comment by EdwardLab** [comment]
approved, thank you
