### ISSUE TITLE
Request GitHub Donate KYC-mail@9916.eu.org

### ISSUE THREAD

**Issue by steven9916** [DigitalPlatDev/US.KG#12497]
Donation amount:

Make sure the title format is "Request GitHub Donate KYC-YOUR_EMAIL@EXAMPLE.COM", After that, you can submit your request! You may also attach a screenshot of the donation receipt for faster processing.

**Comment by EdwardLab** [comment]
Your donation record cannot be found. Please provide a screenshot of your donation. Thank you.
