### ISSUE TITLE
Request GitHub Donate KYC-ivylu0918@163.com

### ISSUE THREAD

**Issue by huilinye** [DigitalPlatDev/US.KG#12490]
Donation amount:

Make sure the title format is "Request GitHub Donate KYC-YOUR_EMAIL@EXAMPLE.COM", After that, you can submit your request! You may also attach a screenshot of the donation receipt for faster processing.
![Screenshot from 2024-10-20 12-54-23](https://github.com/user-attachments/assets/461dd42a-4e71-41f9-86d6-7fe0a8e91732)

**Comment by huilinye** [comment]
I still cannot login. Once I tried to login using this email, it will go to the website for KYC verification and repeat the same process.

**Comment by huilinye** [comment]
> ```
>         Thank you very much for your donation and support for our foundation! We truly appreciate it. You can now sign in to the US.KG Panel to register a new domain.
> ```

Could you help me double check it?

**Comment by EdwardLab** [comment]
Okay I'll check later

**Comment by EdwardLab** [comment]
Hello, Reapproved please check again, thanks
