### ISSUE TITLE
Request GitHub Donate KYC-luoyi2206@gmail.com

### ISSUE THREAD

**Issue by luoyi2206** [DigitalPlatDev/US.KG#12495]
Donation amount:

Make sure the title format is "Request GitHub Donate KYC-YOUR_EMAIL@EXAMPLE.COM", After that, you can submit your request! You may also attach a screenshot of the donation receipt for faster processing.

**Comment by EdwardLab** [comment]
Your donation record cannot be found. Please provide a screenshot of your donation. Thank you.
