### ISSUE TITLE
Request GitHub Donate KYC-isyu12@126.com

### ISSUE THREAD

**Issue by Superyu1** [DigitalPlatDev/US.KG#12508]
Donation amount:

Make sure the title format is "Request GitHub Donate KYC-YOUR_EMAIL@EXAMPLE.COM", After that, you can submit your request! You may also attach a screenshot of the donation receipt for faster processing.

**Comment by EdwardLab** [comment]
Your donation record cannot be found. Please provide a screenshot of your donation. Thank you.
