### ISSUE TITLE
Request GitHub Donate KYC-stellar025@qq.com

### ISSUE THREAD

**Issue by stellar025** [DigitalPlatDev/US.KG#12505]
![20241021104011](https://github.com/user-attachments/assets/5e45b544-7418-48fb-8bc6-19a1599ff5f7)
Donation amount:

Make sure the title format is "Request GitHub Donate KYC-YOUR_EMAIL@EXAMPLE.COM", After that, you can submit your request! You may also attach a screenshot of the donation receipt for faster processing.

**Comment by stellar025** [comment]
![Uploading 20241021105153.png…]()

**Comment by stellar025** [comment]
![20241021105153](https://github.com/user-attachments/assets/d0558975-7319-4731-827b-4a2256d99627)

**Comment by stellar025** [comment]
Why am I still on the kyc page?
![20241021125344](https://github.com/user-attachments/assets/067e9402-8831-49fb-b9d6-a62bf22e1414)

**Comment by EdwardLab** [comment]
I'll check later

**Comment by stellar025** [comment]
it's ok, thank you!
