### ISSUE TITLE
Request GitHub Donate KYC-alanli@mail.io

### ISSUE THREAD

**Issue by alan131** [DigitalPlatDev/US.KG#12510]
Donation amount:

Make sure the title format is "Request GitHub Donate KYC-YOUR_EMAIL@EXAMPLE.COM", After that, you can submit your request! You may also attach a screenshot of the donation receipt for faster processing.

**Comment by EdwardLab** [comment]
Your donation record cannot be found. Please provide a screenshot of your donation and resubmit. Thank you.
