### ISSUE TITLE
Request GitHub Donate KYC-luo20121226@outlook.com

### ISSUE THREAD

**Issue by luoyazhou-cn** [DigitalPlatDev/US.KG#12512]
Donation amount:

Make sure the title format is "Request GitHub Donate KYC-YOUR_EMAIL@EXAMPLE.COM", After that, you can submit your request! You may also attach a screenshot of the donation receipt for faster processing.

**Comment by EdwardLab** [comment]
Hello, Your donation record cannot be found. Thank you.
