### ISSUE TITLE
Request GitHub Donate KYC-vifereo001@notwo.eu.org

### ISSUE THREAD

**Issue by fyx-ssj** [DigitalPlatDev/US.KG#12518]
Donation amount:

Make sure the title format is "Request GitHub Donate KYC-YOUR_EMAIL@EXAMPLE.COM", After that, you can submit your request! You may also attach a screenshot of the donation receipt, thank you!

**Comment by fyx-ssj** [comment]
Request GitHub Donate [KYC-YOUR_EMAIL@EXAMPLE.COM](mailto:KYC-YOUR_EMAIL@EXAMPLE.COM)

**Comment by EdwardLab** [comment]
Your donation record cannot be found. Please provide a screenshot of your donation and resubmit. Thank you.
