### ISSUE TITLE
Request GitHub Donate KYC-yuxiao2729@gmail.com

### ISSUE THREAD

**Issue by 2729813169** [DigitalPlatDev/US.KG#12523]
Donation amount:

Make sure the title format is "Request GitHub Donate KYC-YOUR_EMAIL@EXAMPLE.COM", After that, you can submit your request! You may also attach a screenshot of the donation receipt, thank you!

**Comment by 2729813169** [comment]
![屏幕截图(1)](https://github.com/user-attachments/assets/cd89ba6d-e16b-41e6-bf3f-b185b8967ae1)

**Comment by EdwardLab** [comment]
Your donation record cannot be found. Please provide a screenshot of your donation and resubmit. Thank you.
