### ISSUE TITLE
Request GitHub Donate KYC-d0j2zh4r@nqmo.com

### ISSUE THREAD

**Issue by EnngH** [DigitalPlatDev/US.KG#12544]
Donation amount:

Make sure the title format is "Request GitHub Donate KYC-YOUR_EMAIL@EXAMPLE.COM", After that, you can submit your request! You may also attach a screenshot of the donation receipt, thank you!

**Comment by EdwardLab** [comment]
Your donation record cannot be found. Please provide a screenshot of your donation and resubmit. Thank you.
