### ISSUE TITLE
Request GitHub Donate KYC-sanzdevotp@gmail.com

### ISSUE THREAD

**Issue by Sanzzdev** [DigitalPlatDev/US.KG#12548]
Donation amount:

Make sure the title format is "Request GitHub Donate KYC-sanzdevotp@gmail.com", After that, you can submit your request! You may also attach a screenshot of the donation receipt, thank you!

**Comment by EdwardLab** [comment]
Your donation record cannot be found. Please provide a screenshot of your donation and resubmit. Thank you.
