### ISSUE TITLE
Request GitHub Donate KYC-liutong168@vip.qq.com

### ISSUE THREAD

**Issue by LT000M** [DigitalPlatDev/US.KG#12547]
Donation amount:

Make sure the title format is "Request GitHub Donate KYC-YOUR_EMAIL@EXAMPLE.COM", After that, you can submit your request! You may also attach a screenshot of the donation receipt, thank you!

**Comment by EdwardLab** [comment]
Your donation record cannot be found. Please provide a screenshot of your donation and resubmit. Thank you.
