### ISSUE TITLE
Request GitHub Donate KYC-wu.charles@foxmail.com

### ISSUE THREAD

**Issue by eightwolfs** [DigitalPlatDev/US.KG#12555]
Donation amount:

Make sure the title format is "Request GitHub Donate KYC-YOUR_EMAIL@EXAMPLE.COM", After that, you can submit your request! You may also attach a screenshot of the donation receipt, thank you!

**Comment by EdwardLab** [comment]
Your donation record cannot be found. Please provide a screenshot of your donation and resubmit. Thank you.

**Comment by eightwolfs** [comment]
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
