### ISSUE TITLE
请求GitHub捐赠KYC-lllpx@vip.qq.com

### ISSUE THREAD

**Issue by lllpxxx** [DigitalPlatDev/US.KG#12553]
Donation amount:

Make sure the title format is "Request GitHub Donate KYC-YOUR_EMAIL@EXAMPLE.COM", After that, you can submit your request! You may also attach a screenshot of the donation receipt, thank you!

**Comment by EdwardLab** [comment]
Your donation record cannot be found. Please provide a screenshot of your donation and resubmit. Thank you.
