### ISSUE TITLE
Request GitHub KYC - Your US.KG Panel registered email. 

### ISSUE THREAD

**Issue by kinglee312** [DigitalPlatDev/US.KG#12875]
Username:kunking
Account Registration Email:[LEEKING@gou.to](mailto:LEEKING@gou.to)
Reason for Registering the .US.KG Domain Name:Compared with other more popular domain names, the ".us.kg" domain name is more suitable for me. It is more in line with my name and I like it very much.

**Comment by EdwardLab** [comment]
Pls follow title format
