### ISSUE TITLE
you just want to get the donate,or money?

### ISSUE THREAD

**Issue by lemonfog** [DigitalPlatDev/US.KG#129]
### KYC Using Your GitHub Account

Ensure your GitHub account meets the following requirements:

- [x] I have starred this repository (required).
- [x] Not a new GitHub account; it already has some repositories and stars.
- [x] This is my first US.KG NIC Panel account.
- [x] I promise not to use the domain name for criminal or abusive purposes.
- [x] I understand that GitHub KYC requires a waiting period for review.

**Your Account Details (US.KG NIC Panel):**
- Your full name: lemon fog
- Username: lemon
- Account Registration Email: 1851303357@qq.com
- Reason for Registering the .US.KG Domain Name:  I have an open-source website project and I really need a domain name to provide network access

After submission, we will process your request ASAP.

**Comment by EdwardLab** [comment]
Approved, you may now login to US.KG Panel (We use scripts to automatically approve or deny. If you have any questions, please email contact@nic.us.kg)

**Comment by EdwardLab** [comment]
Approved, you may now login to US.KG Panel (We use scripts to automatically approve or deny. If you have any questions, please email contact@nic.us.kg)

**Comment by EdwardLab** [comment]
The script cannot automatically process your request, please do not edit the title
