### ISSUE TITLE
Request GitHub Donate KYC-

### ISSUE THREAD

**Issue by 7749-lcj** [DigitalPlatDev/US.KG#13382]
Donation amount:

Make sure the title format is "Request GitHub Donate KYC-YOUR_EMAIL@EXAMPLE.COM", After that, you can submit your request! You may also attach a screenshot of the donation receipt, thank you!
![Uploading 微信图片_20241024133601.png…]()

**Comment by EdwardLab** [comment]
Can't find the donation record, please upload a screenshot, thank you
