### ISSUE TITLE
Request GitHub KYC-Tech_Sky@xn--6rtwn.icu

### ISSUE THREAD

**Issue by kj163kj** [DigitalPlatDev/US.KG#135]
### KYC Using Your GitHub Account

Ensure your GitHub account meets the following requirements:

- [Yes] I have starred this repository (required).
- [Yes] Not a new GitHub account; it already has some repositories and stars.
- [Yes] This is my first US.KG NIC Panel account.
- [Yes] I promise not to use the domain name for criminal or abusive purposes.
- [Yes] I understand that GitHub KYC requires a waiting period for review.

**Your Account Details (US.KG NIC Panel):**
- Your full name: Yao GengBin
- Username: Tech_Sky
- Account Registration Email: Tech_Sky@xn--6rtwn.icu
- Reason for Registering the .US.KG Domain Name:For personal blogs

After submission, we will process your request ASAP.

**Comment by EdwardLab** [comment]
Sorry, your GitHub account is too new. Please consider using other methods for KYC, Thanks :) (We use scripts to automatically approve or deny. If you have any questions, please email contact@nic.us.kg)
