### ISSUE TITLE
请求GitHub KYC-mazengxin66@gmail.com

### ISSUE THREAD

**Issue by Jack-ma-hub66** [DigitalPlatDev/US.KG#13814]
使用您的GitHub帐户的KYC我们使用自动脚本来批准请求。请确保您的GitHub帐户满足以下要求（全部为必填项）：我已经为这个存储库加了星标。问题标题必须是：请求GitHub KYC-您的US.KG面板注册电子邮件。这确保了我们的自动脚本可以检测您注册的电子邮件。这不是一个新的GitHub帐户；它有现有的存储库和星星。这是我的第一个US.KG NIC面板帐户。我保证不会将域名用于犯罪或滥用目的。您的帐户详细信息（US.KG NIC面板）：请填写以下信息；否则，您的请求将无法处理：用户名：JackMa900705帐户注册电子邮件：mazengxin66@gmail.com注册的原因。US.KG域名：

**Comment by EdwardLab** [comment]
Use English pls
