### ISSUE TITLE
What does name server mean?

### ISSUE THREAD

**Issue by Meshkat22** [DigitalPlatDev/US.KG#14273]
Hi there!

## I am a newbie. I do not understand what does name server means. What should I fill up those blanks?? Could anyone please help me by giving the info? 

Thanks

**Comment by XingYoi** [comment]
Oh, brother, this is the Domain name, look at the email to fill in, I also encountered a problem, I added a star and they didn't think I added a star when I activated it

**Comment by Meshkat22** [comment]
I do not understand what you are referring to,... Let me provide a screenshot.

<img width="1018" alt="image" src="https://github.com/user-attachments/assets/fe837900-ff76-4403-964d-ab8876788859">

## What does these name servers mean?

Thanks

**Comment by XingYoi** [comment]
This needs to be done in cloudflare, if you need, you can search for tutorials in YouTube, where you have everything you want. And it's very simple

**Comment by Meshkat22** [comment]
Actually, I'm completely new in this. And that's why I'm not understanding the steps. Could you please tell me the logic behind it and what should be done after what? I want to register subdomain and why do I need the Cloudflare?

**Comment by EdwardLab** [comment]
We don't provide general technical guidance. But I think you should learn how domain names work. You need to use any third party DNS platform, such as Cloudflare, FreeDNS, Hostry... they will provide Name Server NS addresses, fill in these vale into the Name Server NS and you can register it. then manage your free domain on these DNS platform

**Comment by EdwardLab** [comment]
I'll close this
