### ISSUE TITLE
Request GitHub KYC-yousefhamdy32323@gmail.com

### ISSUE THREAD

**Issue by SadDevastator** [DigitalPlatDev/US.KG#144]
### KYC Using Your GitHub Account

Ensure your GitHub account meets the following requirements:

- [✔ ] I have starred this repository (required).
- [ ✔] Not a new GitHub account; it already has some repositories and stars.
- [ ✔] This is my first US.KG NIC Panel account.
- [ ✔] I promise not to use the domain name for criminal or abusive purposes.
- [ ✔] I understand that GitHub KYC requires a waiting period for review.

**Your Account Details (US.KG NIC Panel):**
- Your full name: Yousef Tarek Hamdy Ibrahim Ismail
- Username: SadDevastator
- Account Registration Email: yousefhamdy32323@gmail.com
- Reason for Registering the .US.KG Domain Name: personal use

After submission, we will process your request ASAP.

**Comment by EdwardLab** [comment]
Sorry, your GitHub account is too new. Please consider using other methods for KYC, Thanks :) (We use scripts to automatically approve or deny. If you have any questions, please email contact@nic.us.kg)
