### ISSUE TITLE
Request GitHub KYC-jingzhai12@gmail.com

### ISSUE THREAD

**Issue by Alger2020** [DigitalPlatDev/US.KG#149]
### KYC Using Your GitHub Account
 
Ensure your GitHub account meets the following requirements:

- [x] I have starred this repository (required).
- [X] Not a new GitHub account; it already has some repositories and stars.
- [X] This is my first US.KG NIC Panel account.
- [X] I promise not to use the domain name for criminal or abusive purposes.
- [X] I understand that GitHub KYC requires a waiting period for review.

**Your Account Details (US.KG NIC Panel):**
- Your full name: Theresa W Chavez
- Username: jingzhai12@gmail.com
- Account Registration Email: jingzhai12@gmail.com
- Reason for Registering the .US.KG Domain Name:study Exchange

After submission, we will process your request ASAP.

**Comment by EdwardLab** [comment]
Sorry, your GitHub account is too new. Please consider using other methods for KYC, Thanks :) (We use scripts to automatically approve or deny. If you have any questions, please email contact@nic.us.kg)
