### ISSUE TITLE
Request GitHub KYC-ssss65656@gmail.com

### ISSUE THREAD

**Issue by ssl1192** [DigitalPlatDev/US.KG#168]
### KYC Using Your GitHub Account

Ensure your GitHub account meets the following requirements:

- [ ] I have starred this repository (required).
- [ ] Not a new GitHub account; it already has some repositories and stars.
- [ ] This is my first US.KG NIC Panel account.
- [ ] I promise not to use the domain name for criminal or abusive purposes.
- [ ] I understand that GitHub KYC requires a waiting period for review.

**Your Account Details (US.KG NIC Panel):**
- Your full name: ssss u
- Username: ssssu
- Account Registration Email: ssss65656@gmail.com
- Reason for Registering the .US.KG Domain Name:

After submission, we will process your request ASAP.

**Comment by EdwardLab** [comment]
Please star this project (Click the star in the upper right corner)

**Comment by EdwardLab** [comment]
Sorry, your GitHub account is too new. Please consider using other methods for KYC, Thanks :) (We use scripts to automatically approve or deny. If you have any questions, please email contact@nic.us.kg)
