### ISSUE TITLE
Request GitHub KYC-mondispl@gmail.com

### ISSUE THREAD

**Issue by mondisplusdia96** [DigitalPlatDev/US.KG#199]
### KYC Using Your GitHub Account

Ensure your GitHub account meets the following requirements:

- [v] I have starred this repository (required).
- [v] Not a new GitHub account; it already has some repositories and stars.
- [v] This is my first US.KG NIC Panel account.
- [v] I promise not to use the domain name for criminal or abusive purposes.
- [v] I understand that GitHub KYC requires a waiting period for review.

**Your Account Details (US.KG NIC Panel):**
- Your full name: Shuom ondispl
- Username: mondispl
- Account Registration Email: mondispl@gmail.com
- Reason for Registering the .US.KG Domain Name:For academy use

After submission, we will process your request ASAP.

**Comment by EdwardLab** [comment]
Sorry, your GitHub account is too new (Too few stars and repositories). Please consider using other methods for KYC, Thanks :) (We use scripts to automatically approve or deny. If you have any questions, please email contact@nic.us.kg)
