### ISSUE TITLE
Request GitHub KYC-ishpduwu@foxmail.com

### ISSUE THREAD

**Issue by IsHPDuwu** [DigitalPlatDev/US.KG#276]
### KYC Using Your GitHub Account

Ensure your GitHub account meets the following requirements:

- [ 1 ] I have starred this repository (required).
- [ 1 ] Not a new GitHub account; it already has some repositories and stars.
- [ 1 ] This is my first US.KG NIC Panel account.
- [ 1 ] I promise not to use the domain name for criminal or abusive purposes.
- [ 1 ] I understand that GitHub KYC requires a waiting period for review.

**Your Account Details (US.KG NIC Panel):**
- Your full name: HPD QU
- Username: IsHPDovo
- Account Registration Email: ishpduwu@foxmail.com
- Reason for Registering the .US.KG Domain Name: Set up my own website.

After submission, we will process your request ASAP.

**Comment by EdwardLab** [comment]
Sorry, your GitHub account is too new (too few stars and repositories). Please consider using other methods for KYC. Thanks! (We use scripts to automatically approve or deny. If you have any questions or think this is an error, please feel free to email us at contact@nic.us.kg.)
