### ISSUE TITLE
Request GitHub KYC-wlor0623@gmail.com

### ISSUE THREAD

**Issue by localbobs** [DigitalPlatDev/US.KG#413]
### KYC Using Your GitHub Account

We use automated scripts to approve requests. Please make sure your GitHub account meets the following requirements to avoid delays:

- [ ] I have starred this repository (required).
- [ ] The issue title must be: Request GitHub KYC - <Your US.KG Panel registered email>. This ensures our automated script can detect your registered email.
- [ ] This is not a new GitHub account; it has existing repositories and stars.
- [ ] This is my first US.KG NIC Panel account.
- [ ] I promise not to use the domain name for criminal or abusive purposes.
- [ ] I understand that GitHub KYC requires a waiting period for review.

**Your Account Details (US.KG NIC Panel):**

Please fill out the following information; otherwise, your request will not be processed:
- Your full name: 
- Username: 
- Account Registration Email: 
- Reason for Registering the .US.KG Domain Name:

**Comment by localbobs** [comment]
close

**Comment by localbobs** [comment]
close

**Comment by EdwardLab** [comment]
Sorry, your GitHub account is too new (Too few stars and repositories). Please consider using other methods for KYC, Thanks :) If you have further questions, please feel free to contact us (We use scripts to automatically approve or deny. If you have any questions, please email contact@nic.us.kg)
