### ISSUE TITLE
Request GitHub KYC-root@tygxfile.eu.org

### ISSUE THREAD

**Issue by panjnor** [DigitalPlatDev/US.KG#437]

**Comment by EdwardLab** [comment]
Sorry, your GitHub account is too new (Too few stars and repositories). Please consider using other methods for KYC, Thanks :) If you have further questions, please feel free to contact us (We use scripts to automatically approve or deny. If you have any questions, please email contact@nic.us.kg)

**Comment by EdwardLab** [comment]
Sorry, your GitHub account is too new (Too few stars and repositories). Please consider using other methods for KYC, Thanks :) If you have further questions, please feel free to contact us (We use scripts to automatically approve or deny. If you have any questions, please email contact@nic.us.kg)
