### ISSUE TITLE
Request GitHub KYC-us.kg@xrzyun.eu.org

### ISSUE THREAD

**Issue by xrz-cloud** [DigitalPlatDev/US.KG#467]
### KYC Using Your GitHub Account

We use automated scripts to approve requests. Please make sure your GitHub account meets the following requirements to avoid delays:

- [x] I have starred this repository (required).
- [x] The issue title must be: Request GitHub KYC - <Your US.KG Panel registered email>. This ensures our automated script can detect your registered email.
- [x] This is not a new GitHub account; it has existing repositories and stars.
- [x] This is my first US.KG NIC Panel account.
- [x] I promise not to use the domain name for criminal or abusive purposes.
- [x] I understand that GitHub KYC requires a waiting period for review.

**Your Account Details (US.KG NIC Panel):**

Please fill out the following information; otherwise, your request will not be processed:
- Your full name: aoi mio
- Username: aoimio
- Account Registration Email: us.kg@xrzyun.eu.org
- Reason for Registering the .US.KG Domain Name: To share my repos that can have a better style and clearer way to show the codes and help info. This domain is not long so that it is just suitable for me. And for learning web dev and testing my pages deploy. 
Maybe I want to say this github account was created on 2020-03-31, so I have used it for 4 years, which can prove my account is not new.
Though my account's homepage has not repos that have many stars, I own [this repo](https://github.com/bili-vd-bak/biliroaming-ts-server-vercel) and it has a ~50 stars and ~60 forks. And my public repo was almost all published as the org [bili-vd-bak](https://github.com/bili-vd-bak).
Also, I'm devoted to contributing to some repos, such as [CloudflareWarpSpeedTest](https://github.com/peanut996/CloudflareWarpSpeedTest) [contributor and its aur package's maintainer] and [bilibili-API-collect(video platform's API collections)](https://github.com/SocialSisterYi/bilibili-API-collect) [contributor].
So, I think my request is supposed to be accept. If not, I want a clear explanation instead of the same "Sorry, your GitHub account is too new (too few stars and repositories).". Thanks!

**Comment by xrz-cloud** [comment]
To let you not miss my ideas, I would send this again.  
This github account was created on 2020-03-31, so I have used it for 4 years, which can prove my account is not new.
Though my account's homepage has not repos that have many stars, I own [this repo](https://github.com/bili-vd-bak/biliroaming-ts-server-vercel) and it has a ~50 stars and ~60 forks. And my public repo was almost all published as the org [bili-vd-bak](https://github.com/bili-vd-bak).
Also, I'm devoted to contributing to some repos, such as [CloudflareWarpSpeedTest](https://github.com/peanut996/CloudflareWarpSpeedTest) [contributor and its aur package's maintainer] and [bilibili-API-collect(video platform's API collections)](https://github.com/SocialSisterYi/bilibili-API-collect) [contributor].
So, I think my request is supposed to be accept. If not, I want a clear explanation instead of the same "Sorry, your GitHub account is too new (too few stars and repositories).". Thanks.

**Comment by EdwardLab** [comment]
Approved, you may now sign in to US.KG Panel and get a new domain!!!  :)  (We use scripts to automatically approve or deny. If you have any questions, please email contact@nic.us.kg)
