### ISSUE TITLE
Request GitHub KYC-22.m.faisal@gmail.com

### ISSUE THREAD

**Issue by MVaisal** [DigitalPlatDev/US.KG#70]
### KYC Using Your GitHub Account

Ensure your GitHub account meets the following requirements:

- [x] I have starred this repository (required).
- [x] Not a new GitHub account; it already has some repositories and stars.
- [x] This is my first US.KG NIC Panel account.
- [x] I promise not to use the domain name for criminal or abusive purposes.
- [x] I understand that GitHub KYC requires a waiting period for review.

**Your Account Details (US.KG NIC Panel):**
- Your full name: Muhammad Faisal
- Username: bucoks1
- Account Registration Email: 22.m.faisal@gmail.com
- Reason for Registering the .US.KG Domain Name: I want to use for my Website
After submission, we will process your request ASAP.

**Comment by EdwardLab** [comment]
Sorry, your GitHub account is too new. Please consider using other methods for KYC, Thanks :) (We use scripts to automatically approve or deny. If you have any questions, please email contact@nic.us.kg)
